services:
  cloudflared:
    image: cloudflare/cloudflared:2026.5.2@sha256:12ff5c6992a9863db4da270746af7c244bcaee49353039af8104268a18d6c4f0
    container_name: cloudflared
    environment:
      - TZ=America/Vancouver
      - TUNNEL_TOKEN=${API_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
