networks:
  cloudflared:
    external: true
  app_network:
    external: true
volumes:
  uhf-server-data:

services:
  uhf-server:
    image: swapplications/uhf-server:2.0.0@sha256:dcb832f910be8d85b67a25adb7cf12defb9e8e5ea1117e2c1a03fd5db4a82027
    container_name: uhf-server
    ports:
      - 63890:63890
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - /srv/data/media/tv/iptv:/recordings
      - uhf-server-data:/var/lib/uhf-server
    command: uhf-server --port 63890 --recordings-dir /recordings --password ${PASSWORD}
    stop_grace_period: 30s
    networks:
      - cloudflared
      - app_network
