networks:
  cloudflared:
    external: true
  app_network:
    external: true
volumes:
  uhf-server-data:

services:
  uhf-server:
    image: swapplications/uhf-server:1.6.0@sha256:01e9fc1fc2725e8f10973cb8aa06638e9c82dcb64e4d5ae01b58f7651fe1e3ba
    container_name: uhf-server
    ports:
      - 63890:63890
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - /srv/data/media/tv/iptv:/recordings
      - uhf-server-data:/var/lib/uhf-server
    command: uhf-server --port 63890 --recordings-dir /recordings --password ${PASSWORD}
    stop_grace_period: 30s
    networks:
      - cloudflared
      - app_network
