services:
  tailscale:
    image: tailscale/tailscale:v1.98.10@sha256:cdf5612ded5be1344f1a704b8c5e53496db97376bb533e5e15f141e48bf60cc0
    container_name: tailscale-subnet-router
    hostname: docker-subnet-router
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_ROUTES=${TS_ROUTES}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-routes
      - TS_USERSPACE=false
    volumes:
      - tailscale_data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped

volumes:
  tailscale_data: