networks:
  app_network:
    external: true

volumes:
  postgres_data:
    external: true
    name: postgres_postgres_data
  pgadmin-data:
    external: true
    name: postgres_pgadmin-data

services:
  db:
    image: postgres:17.9@sha256:2a0d0fe14825b0939f78a8cad5cd4e6aa68bf94d0e5dd96e24b6d23af4315545
    container_name: postgres_db
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 60s
      timeout: 5s
      retries: 5
  pgadmin_service:
    image: dpage/pgadmin4:9.14.0@sha256:ff557f69d9808085dc3554f56c1b06a36ac8cddabe4485212920b9604261abdb
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80"
    networks:
      - app_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
