networks:
  app_network:
    external: true

volumes:
  postgres_data:
    external: true
    name: postgres_postgres_data
  pgadmin-data:
    external: true
    name: postgres_pgadmin-data

services:
  db:
    image: postgres:17.9@sha256:6fd8445ad3e5c8413b7a2f002c639ea5581d633317d142e556506e62d0018e24
    container_name: postgres_db
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 60s
      timeout: 5s
      retries: 5
  pgadmin_service:
    image: dpage/pgadmin4:9.13.0@sha256:d243a4bcc02d2ee6b447c601692813531d2d0fbca18b583d9f7f9658da835d81
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80"
    networks:
      - app_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
