volumes:
  music-assistant-server-data:
    external: true
    name: home-assistant_music-assistant-server-data

services:
  # Opt-in service. Run with:
  # docker compose -f compose.yaml -f compose.music-assistant.yaml up -d music-assistant-server
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta@sha256:fcdd521b3cc013ae2dc3d79e18e58c93ccd15e5ab96e8a62b59b83d4ee9e6bea
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - music-assistant-server-data:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
