volumes:
  music-assistant-server-data:
    external: true
    name: home-assistant_music-assistant-server-data

services:
  # Opt-in service. Run with:
  # docker compose -f compose.yaml -f compose.music-assistant.yaml up -d music-assistant-server
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta@sha256:f874a002b46f383c8b729570f8749cc86e04d665d337de5747e792a90a73ec67
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - music-assistant-server-data:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
