networks:
  app_network:
    external: true

volumes:
  mosquito-data:
    external: true
    name: mosquitto_mosquito-data

services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:38c0da4f2ef84284d47b3b3eeea1cb3bdeabe81ee10caf0cd5c5ff61ee3ea408
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9011:9001
    volumes:
      - mosquito-data:/mosquitto
      - mosquito-data:/mosquitto/data
      - mosquito-data:/mosquitto/log
    networks:
      - app_network
