networks:
  ha_signal_private:
    external: true
  signal_egress:

volumes:
  signal-cli-config:
    name: signal-cli-rest

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.100@sha256:2399d449123cdad56c4d859277e3b9127e1a00c4d2ab4601c239882609286cf8
    restart: unless-stopped
    volumes:
      - signal-cli-config:/home/.local/share/signal-cli
    networks:
      ha_signal_private:
        aliases:
          - signal-rest
      signal_egress:
    expose:
      - "8080"
