networks:
  app_network:
    external: true
  ha_signal_private:
    external: true

volumes:
  nginxproxymanager-data:
    external: true
    name: nginxproxymanager_nginxproxymanager-data

services:
  app:
    image: "jc21/nginx-proxy-manager:2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    volumes:
      - nginxproxymanager-data:/data
      - nginxproxymanager-data:/etc/letsencrypt
    networks:
      - app_network
      - ha_signal_private
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
